### ISSUE TITLE
Cannot save trained model to a saved_model

### ISSUE THREAD

**Issue by Arix12** [Burf/TFDetection#6]
I am training with either effdet_d0 or yolo_v4 the train itself is OK but right after calling fit I try to save the model using model.save('temp/') but I get the following error: (using model.save_weights("model.h5") works fine)

Traceback (most recent call last):
  File "/home/sergey/eff_det_open_source/TFDetection/usage/train.py", line 190, in <module>
    tf2trt(model, "converted_model.trt")
  File "/home/sergey/eff_det_open_source/TFDetection/tfdet/export/tensorrt.py", line 28, in tf2trt
    model.save(temp_path)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 264, in _reconstruct
    y = func(*args)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 263, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/sergey/miniconda3/envs/old_tf_ver/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.RLock' object

**Comment by Burf** [comment]
See https://github.com/Burf/TFDetection/blob/main/usage/export/object_detection.ipynb.
Rather than directly converting from tf to tensorrt, it is better to convert via onnx.
